sudo: false
language: node_js
node_js:
  - "14"

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
    - dist
    - .cache

stages:
  - Build

jobs:
  fast_finish: true

  include:
    - stage: Build
      name: Lint and Build
      before_install: npm install --global yarn
      install: yarn
      script:
        - yarn lint:js || travis_terminate 1
        - yarn lint:markdown || travis_terminate 1
        - yarn lint:social || travis_terminate 1
        - yarn build || travis_terminate 1
        - yarn lint:links || travis_terminate 1
