language: node_js
node_js:
  - "14"

cache:
  yarn: true
  directories:
    - node_modules
    - dist
    - .cache

stages:
  - Build

jobs:
  fast_finish: true

  include:
    - stage: Build
      name: Lint and Build
      script:
        - yarn lint:js || travis_terminate 1
