branches:
  only:
    - master
    - develop
language: node_js
node_js:
  - "6"
script:
  - bash ./scripts/deploy.sh
sudo: required
cache: yarn
install:
  - npm i yarn -g
  - yarn
  - sudo pip install proselint
