branches:
  only:
    - master
    - develop
language: node_js
node_js:
  - "8"
sudo: required
install:
  - npm install --global yarn
  - yarn
  - sudo pip install proselint
script:
  - bash ./src/scripts/deploy.sh
