name: Build

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint:js
      - run: yarn lint:markdown
      - run: yarn lint:social
